#!/bin/sh
# Xsetup - run as root before the login dialog appears

# AOSC OS: # Call the common screen and touch rotation script
if [ -x /etc/X11/xinit/xinitrc.d/90-auto-rotate.sh ]; then
    /etc/X11/xinit/xinitrc.d/90-auto-rotate.sh
fi
